---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clusterhealth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterhealth
subjects:
- kind: ServiceAccount
  name: clusterhealth
  namespace: kube-system

