---
# Source: sol-collector/templates/secret-bmc.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: atscale-sol-collector-bmc
  labels:
    app.kubernetes.io/name: sol-collector
    helm.sh/chart: sol-collector-0.1.0
    app.kubernetes.io/instance: atscale
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
data:
  redfish_user: ZGVmYXVsdHVzZXI=
  redfish_password: MHBlbkJtYzE=
  ipmi_user: ZGFmYXVsdHVzZXI=
  ipmi_password: MHBlbkJtYzE=
