{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bmc-sel-collector.serviceAccountName" . }}
  labels:
{{ include "bmc-sel-collector.labels" . | indent 4 }}
{{- end -}}
