apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ras-tracer
  namespace: mgmt
  labels:
    k8s-app: ras-tracer
spec:
  selector:
    matchLabels:
      name: ras-tracer
  template:
    metadata:
      labels:
        name: ras-tracer
    spec:
      hostNetwork: true
      containers:
      - name: ras-trace
        image: prt-registry.sova.intel.com/sandstone:jasper-vtd-detector-v0.1
        command: ["/usr/bin/bash"]
        args: ["-c", "echo enabling ras tracing; mkdir /sys/kernel/debug/tracing/instances/rastrace; cd /sys/kernel/debug/tracing/instances/rastrace; echo 1 > events/ras/mc_event/enable; cat trace_pipe"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: dbus
          mountPath: /var/run/dbus
          readOnly: true
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
        - name: journal
          mountPath: /journal
          readOnly: true
        - mountPath: /sys
          name: hostrootsys
      volumes:
        - name: hostroot
          hostPath:
            path: /tmp
            type: Directory
        - name: hostrootsys
          hostPath:
            path: /sys
        - name: hostrootucode
          hostPath:
            path: /lib/firmware/intel-ucode
        - name: dbus
          hostPath:
            path: /var/run/dbus
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: journal
          hostPath:
            path: /var/log/journal
