## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: true
  servers: 3
  globalOutstandingLimit: 5000
  nodeSelector:
    nodetype: telemetry
  persistence:
    # TODO: Setup disk sizes based on availability on cluster
    dataDirSize: 3967Mi
    dataDirStorageClass: local-storage
    dataLogDirSize: 975Mi
    dataLogDirStorageClass: local-storage
  resources:
    requests:
      memory: 2Gi 
## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  nodeSelector:
    nodetype: telemetry
  brokers: 3
  configurationOverrides:
    "offsets.topic.replication.factor": "2"
    "default.replication.factor": "2"
    "retention.ms": "604800000"
    "replica.fetch.max.bytes": "10485760"
    "message.max.bytes": "10485760"
    "num.partitions": "24"
  heapOptions: "-Xms6G -Xmx6G"
  nodeport:
    enabled: true
  persistence:
    # TODO: Setup disk sizes based on availability on cluster
    storageClass: local-storage
    size: 48Gi
  resources:
    requests:
      memory: 32Gi

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: false

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: false

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  enabled: false

## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: true
  nodeSelector:
    nodetype: telemetry

## ------------------------------------------------------
## Control Center
## ------------------------------------------------------
cp-control-center:
  enabled: false
