apiVersion: apps/v1
kind:   StatefulSet
metadata:
  name: filebeat-bridge-{{.Values.name}}
  labels:
    k8s-app: filebeat-bridge-{{.Values.name}}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: {{.Values.replicas}}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      k8s-app: filebeat-bridge-{{.Values.name}}
  serviceName: filebeat-bridge
  template:
    metadata:
      labels:
        k8s-app: filebeat-bridge-{{.Values.name}}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      nodeSelector:
        filebeat-bridge: "true"
      containers:
      - name: filebeat-bridge
        image: docker.elastic.co/beats/filebeat:7.7.0
        command: ["bash"]
        args: ["-c", "/etc/filebeat.yml",
              "-e"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

  volumeClaimTemplates:
  - metadata:
      name: fluentd-buffers
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{.Values.storage.size}}
      storageClassName: {{.Values.storage.class}} 
