apiVersion: batch/v1
kind: Job
metadata:
  name: ipu-pnp-stream
  namespace: ipu-pnp-icx-dry-run
  annotations:
    time: time15
spec:
  template:
    metadata:
      labels:
        app: ipu-pnp-stream
    spec:
      imagePullSecrets:
      - name: jenkins-docker
      containers:
      - image: pnp-harbor.sh.intel.com/pnp/stream:latest
        imagePullPolicy: Always
        name: jenkins-stream
        command: ["./docker_stream.sh"]
        securityContext:
          privileged: true
      nodeSelector: 
        kubernetes.io/hostname: spiv-pnp-4f-ipu-icx-backup
      restartPolicy: Never
