---
# Source: prometheus-blackbox-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atscale-prometheus-blackbox-exporter
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: atscale
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-blackbox-exporter-4.10.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: atscale
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-blackbox-exporter
        app.kubernetes.io/instance: atscale
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: prometheus-blackbox-exporter-4.10.1
      annotations:
        checksum/config: 42db4f12727be4d4f1c06af9ec4e4364f12cd659cbc3a43c320ab3819c95f118
    spec:
      serviceAccountName: atscale-prometheus-blackbox-exporter
      nodeSelector:
        kafka: "true"

      restartPolicy: Always
      containers:      
        - name: blackbox-exporter
          image: "prom/blackbox-exporter:v0.18.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_RAW"]
          env:
          args:
            - "--config.file=/config/blackbox.yaml"
          resources:
            {}
          ports:
            - containerPort: 9115
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:      
        - name: config
          configMap:
            name: atscale-prometheus-blackbox-exporter
