---
# Source: prometheus-blackbox-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: atscale
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-blackbox-exporter-4.10.1
  name: atscale-prometheus-blackbox-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: atscale-prometheus-blackbox-exporter
subjects:
  - kind: ServiceAccount
    name: atscale-prometheus-blackbox-exporter
