---
# Source: fluentd-prom/templates/fluentd-prom-ds.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-prom
  namespace: mgmt
  labels:
    k8s-app: fluentd-prom
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
# Source: fluentd-prom/templates/fluentd-prom-ds.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-prom
  labels:
    k8s-app: fluentd-prom
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
# Source: fluentd-prom/templates/fluentd-prom-ds.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-prom
  labels:
    k8s-app: fluentd-prom
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-prom
  namespace: mgmt
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-prom
  apiGroup: ""
---
# Source: fluentd-prom/templates/fluentd-prom-ds.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-prom-v2.2.1
  namespace: mgmt
  labels:
    k8s-app: fluentd-prom
    version: v2.2.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
        #replicas: 2
  selector:
    matchLabels:
      k8s-app: fluentd-prom
      version: v2.2.1
  template:
    metadata:
      labels:
        k8s-app: fluentd-prom
        kubernetes.io/cluster-service: "true"
        version: v2.2.1
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      # Removing priority class to let the pods run in *-mgmt namespace instead of kube-system
      # priorityClassName: system-node-critical
      serviceAccountName: fluentd-prom
      containers:
      - name: fluentd-prom
        ports:
        - name: metrics
          containerPort: 24231
          protocol: TCP
        image: sraghav1/fluentd-plugins:v3.0.2
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
        - name: pub-logs
          mountPath: /pub/logs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-prom-config-v0.1.6
      - name: pub-logs
        hostPath:
          path: /pub/logs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20%
    type: RollingUpdate
