---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: opcm-monitor
  labels:
    name: opcm-monitor
    type: node
spec:
  selector:
    matchLabels:
      name: opcm-collector
  namespaceSelector:
    matchNames:
    - monitoring
  podMetricsEndpoints:
  - port: metrics
    interval: 10s
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
