apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-std-retain
reclaimPolicy: Retain

provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
