{
 "title": "Admin Monitor Alerts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "a001master001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001master001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001master001\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master001\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001master001\"}  - node_filesystem_avail_bytes{instance=~\"a001master001\"})*100/node_filesystem_size_bytes{instance=~\"a001master001\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001master002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001master002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001master002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001master002\"}  - node_filesystem_avail_bytes{instance=~\"a001master002\"})*100/node_filesystem_size_bytes{instance=~\"a001master002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001master003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001master003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001master003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001master003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001master003\"}  - node_filesystem_avail_bytes{instance=~\"a001master003\"})*100/node_filesystem_size_bytes{instance=~\"a001master003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "a001kafkainfra001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001kafkainfra001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001kafkainfra001\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra001\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001kafkainfra001\"}  - node_filesystem_avail_bytes{instance=~\"a001kafkainfra001\"})*100/node_filesystem_size_bytes{instance=~\"a001kafkainfra001\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001kafkainfra002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001kafkainfra002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001kafkainfra002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001kafkainfra002\"}  - node_filesystem_avail_bytes{instance=~\"a001kafkainfra002\"})*100/node_filesystem_size_bytes{instance=~\"a001kafkainfra002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001kafkainfra003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001kafkainfra003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001kafkainfra003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001kafkainfra003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001kafkainfra003\"}  - node_filesystem_avail_bytes{instance=~\"a001kafkainfra003\"})*100/node_filesystem_size_bytes{instance=~\"a001kafkainfra003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "OOB Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "a001oobinfra001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "a001oobinfra002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001oobinfra002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001oobinfra002\"}  - node_filesystem_avail_bytes{instance=~\"a001oobinfra002\"})*100/node_filesystem_size_bytes{instance=~\"a001oobinfra002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001oobinfra003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001oobinfra003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001oobinfra003\"}  - node_filesystem_avail_bytes{instance=~\"a001oobinfra003\"})*100/node_filesystem_size_bytes{instance=~\"a001oobinfra003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001oobinfra004",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra004\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra004\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001oobinfra004\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra004\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001oobinfra004\"}  - node_filesystem_avail_bytes{instance=~\"a001oobinfra004\"})*100/node_filesystem_size_bytes{instance=~\"a001oobinfra004\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001oobinfra005",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra005\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra005\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001oobinfra005\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra005\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001oobinfra005\"}  - node_filesystem_avail_bytes{instance=~\"a001oobinfra005\"})*100/node_filesystem_size_bytes{instance=~\"a001oobinfra005\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001oobinfra006",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001oobinfra006\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra006\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001oobinfra006\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001oobinfra006\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001oobinfra006\"}  - node_filesystem_avail_bytes{instance=~\"a001oobinfra006\"})*100/node_filesystem_size_bytes{instance=~\"a001oobinfra006\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "a001worker001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker001\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker001\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker001\"}  - node_filesystem_avail_bytes{instance=~\"a001worker001\"})*100/node_filesystem_size_bytes{instance=~\"a001worker001\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001worker002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker002\"}  - node_filesystem_avail_bytes{instance=~\"a001worker002\"})*100/node_filesystem_size_bytes{instance=~\"a001worker002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001worker003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker003\"}  - node_filesystem_avail_bytes{instance=~\"a001worker003\"})*100/node_filesystem_size_bytes{instance=~\"a001worker003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001worker004",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker004\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker004\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker004\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker004\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker004\"}  - node_filesystem_avail_bytes{instance=~\"a001worker004\"})*100/node_filesystem_size_bytes{instance=~\"a001worker004\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001worker005",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker005\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker005\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker005\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker005\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker005\"}  - node_filesystem_avail_bytes{instance=~\"a001worker005\"})*100/node_filesystem_size_bytes{instance=~\"a001worker005\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001worker006",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001worker006\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker006\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001worker006\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001worker006\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001worker006\"}  - node_filesystem_avail_bytes{instance=~\"a001worker006\"})*100/node_filesystem_size_bytes{instance=~\"a001worker006\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "ELK Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "a001elkmaster001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkmaster001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkmaster001\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster001\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkmaster001\"}  - node_filesystem_avail_bytes{instance=~\"a001elkmaster001\"})*100/node_filesystem_size_bytes{instance=~\"a001elkmaster001\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkmaster002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkmaster002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkmaster002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkmaster002\"}  - node_filesystem_avail_bytes{instance=~\"a001elkmaster002\"})*100/node_filesystem_size_bytes{instance=~\"a001elkmaster002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkmaster003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkmaster003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkmaster003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkmaster003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkmaster003\"}  - node_filesystem_avail_bytes{instance=~\"a001elkmaster003\"})*100/node_filesystem_size_bytes{instance=~\"a001elkmaster003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "ELK Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "a001elkworker001",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker001\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker001\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker001\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker001\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker001\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker001\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker002",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker002\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker002\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker002\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker002\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker002\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker002\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker003",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker003\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker003\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker003\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker003\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker003\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker003\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker004",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker004\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker004\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker004\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker004\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker004\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker004\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker004\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker005",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker005\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker005\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker005\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker005\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker005\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker005\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker005\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker006",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker006\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker006\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker006\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker006\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker006\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker006\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker006\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker007",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker007\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker007\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker007\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker007\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker007\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker007\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker007\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker008",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker008\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker008\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker008\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker008\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker008\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker008\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker008\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker009",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker009\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker009\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker009\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker009\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker009\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker009\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker009\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker010",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker010\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker010\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker010\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker010\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker010\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker010\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker010\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker011",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker011\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker011\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker011\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker011\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker011\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker011\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker011\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker012",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker012\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker012\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker012\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker012\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker012\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker012\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker012\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker013",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker013\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker013\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker013\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker013\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker013\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker013\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker013\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker014",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker014\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker014\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker014\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker014\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker014\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker014\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker014\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker015",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker015\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker015\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker015\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker015\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker015\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker015\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker015\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker016",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker016\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker016\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker016\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker016\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker016\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker016\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker016\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker017",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker017\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker017\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker017\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker017\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker017\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker017\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker017\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker018",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker018\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker018\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker018\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker018\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker018\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker018\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker018\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker019",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker019\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker019\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker019\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker019\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker019\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker019\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker019\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker020",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker020\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker020\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker020\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker020\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker020\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker020\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker020\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker021",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker021\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker021\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker021\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker021\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker021\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker021\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker021\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker022\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker022\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker022\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker022\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker022\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker022\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker022\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker023",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker023\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker023\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker023\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker023\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker023\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker023\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker023\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001elkworker024",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\", instance=~\"a001elkworker024\"}[1h])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(({__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker024\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=~\"a001elkworker024\"})*100)/{__name__=~\"node_memory_MemTotal.*\",instance=~\"a001elkworker024\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"a001elkworker024\"}  - node_filesystem_avail_bytes{instance=~\"a001elkworker024\"})*100/node_filesystem_size_bytes{instance=~\"a001elkworker024\", mountpoint!~\".*(/var|/logs|/boot|/opt|/run|/home).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "ELK Cluster Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(min(elasticsearch_filesystem_data_size_bytes{es_data_node=\"true\"}) by (host)) - sum(min(elasticsearch_filesystem_data_available_bytes{es_data_node=\"true\"}) by (host))) / (0.75*sum(min(elasticsearch_filesystem_data_size_bytes{es_data_node=\"true\"}) by (host)))",
     "legendFormat": "Total Disk Usage"
    }
   ]
  }
 ]
}