{
 "title": "Control Plane Usage alert",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "a001telekafka001",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telekafka001\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telekafka001\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka001\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telekafka001\"} - node_filesystem_avail_bytes{instance=\"a001telekafka001\"})*100/node_filesystem_size_bytes{instance=\"a001telekafka001\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001telemaster001",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telemaster001\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telemaster001\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster001\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telemaster001\"} - node_filesystem_avail_bytes{instance=\"a001telemaster001\"})*100/node_filesystem_size_bytes{instance=\"a001telemaster001\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001telekafka002",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telekafka002\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telekafka002\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka002\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telekafka002\"} - node_filesystem_avail_bytes{instance=\"a001telekafka002\"})*100/node_filesystem_size_bytes{instance=\"a001telekafka002\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001telemaster002",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telemaster002\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telemaster002\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster002\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telemaster002\"} - node_filesystem_avail_bytes{instance=\"a001telemaster002\"})*100/node_filesystem_size_bytes{instance=\"a001telemaster002\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001telekafka003",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telekafka003\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telekafka003\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telekafka003\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telekafka003\"} - node_filesystem_avail_bytes{instance=\"a001telekafka003\"})*100/node_filesystem_size_bytes{instance=\"a001telekafka003\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001telemaster003",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001telemaster003\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001telemaster003\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001telemaster003\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001telemaster003\"} - node_filesystem_avail_bytes{instance=\"a001telemaster003\"})*100/node_filesystem_size_bytes{instance=\"a001telemaster003\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001teleprom001",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001teleprom001\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom001\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001teleprom001\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom001\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001teleprom001\"} - node_filesystem_avail_bytes{instance=\"a001teleprom001\"})*100/node_filesystem_size_bytes{instance=\"a001teleprom001\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001teleprom002",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001teleprom002\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom002\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001teleprom002\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom002\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001teleprom002\"} - node_filesystem_avail_bytes{instance=\"a001teleprom002\"})*100/node_filesystem_size_bytes{instance=\"a001teleprom002\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "a001teleprom003",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-100*rate(node_cpu_seconds_total{mode=\"idle\",instance=\"a001teleprom003\"}[10m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "({__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom003\"} - {__name__=~\"node_memory_MemAvailable.*\",instance=\"a001teleprom003\"})* 100 / {__name__=~\"node_memory_MemTotal.*\",instance=\"a001teleprom003\"} ",
     "legendFormat": "Memory"
    },
    {
     "expr": "min((node_filesystem_size_bytes{instance=\"a001teleprom003\"} - node_filesystem_avail_bytes{instance=\"a001teleprom003\"})*100/node_filesystem_size_bytes{instance=\"a001teleprom003\", mountpoint!~\".*(/var/local/ucode|/var/local/common|/dev/fd|/boot|/run).*\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}