{
 "title": "DTS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30" },
   {
    "name": "nodes",
    "label": "nodes",
    "query": "r01s01|r01s02|r01s03|r01s04|r03s17|r03s18|r05s08|r05s09|r05s17|r08s20|r10s01|r10s02|r10s03|r10s05|r10s12|r10s13|r10s14|r10s15|r13s01|r15s01"
   },
   { "name": "Delta", "label": "Delta", "query": "20" }
  ]
 },
 "panels": [
  {
   "title": "Max- Min > Delta in 1h Window",
   "type": "graph",
   "gridPos": { "h": 17, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, ((max_over_time(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[1h]) - min_over_time(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[1h])) > $Delta))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "DTS Temperature - Delta over 20s Window > 30C",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "topk(15,delta(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[20s]) > $Delta)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "DTS Temperature - Delta over 1m Window > 30C",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "topk(15,delta(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[1m]) > $Delta)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "DTS Temperature - Delta over 5m Window > 30C",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "topk(15,delta(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[5m]) > $Delta)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "DTS Temperature - Delta over 1 Hour Window > 30C",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "topk(15,delta(ipmi_temperature_celsius{name=~\"DTS.*\", instance=~\"$nodes\"}[1h]) > $Delta)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  }
 ]
}