{
 "title": "Fluentd Metrics",
 "description": "Checks if remote elastic to able to handle data from all the nodes. (Source: https://gitlab.devtools.intel.com/sandstone/cluster-infra/tree/master/k8s/telemetry/dashboards/grafana/target-fluentd-es)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values(fluentd_output_status_emit_count, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Input records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_input_status_num_records_total{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd output write count (total)",
   "type": "graph",
   "description": "Each writes involve writing one chunk of data. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_write_count{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Output errors rate per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_num_errors{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Output buffer bytes",
   "type": "graph",
   "description": "Higher buffer indicates data backing up in fluent, usually due to errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_total_bytes{container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Output retry count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_retry_count{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total number of errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_num_errors{container=\"$container\"})"
    }
   ]
  },
  {
   "title": "Output Records Emitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_emit_records{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "fluentd_output_status_buffer_queue_length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length{container=\"$container\"})"
    }
   ]
  },
  {
   "title": "fluentd_output_status_flush_time_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_flush_time_count{container=\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "fluentd_output_status_rollback_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_rollback_count)"
    }
   ]
  }
 ]
}