{
 "title": "Kafka - Java Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "jvm_memory_usage_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage_used_bytes{job!~\".*headless.*\"}",
     "legendFormat": "{{pod}} {{area}}"
    }
   ]
  },
  {
   "title": "jvm_mempool_peakusage_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_mempool_peakusage_used{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_lastgcinfo_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_lastgcinfo_duration{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_lastgcinfo_memoryusagebeforegc_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_lastgcinfo_memoryusagebeforegc_used{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{key}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_collectiontime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collectiontime{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_lastgcinfo_memoryusageaftergc_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_lastgcinfo_memoryusageaftergc_used{job!~\"headless\"}",
     "legendFormat": "{{pd}} {{key}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_usage_committed_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage_committed_bytes{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{area}}"
    }
   ]
  },
  {
   "title": "jvm_mempool_peakusage_committed",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_mempool_peakusage_committed{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_mempool_usage_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_mempool_usage_max{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_mempool_collectionusage_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_mempool_collectionusage_max{job!~\"headless\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "jvm_mempool_collectionusagethresholdcount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_mempool_collectionusagethresholdcount{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_lastgcinfo_memoryusageaftergc_committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_lastgcinfo_memoryusageaftergc_committed{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{key}} {{name}}"
    }
   ]
  },
  {
   "title": "jvm_gc_lastgcinfo_gcthreadcount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_lastgcinfo_gcthreadcount{job!~\"headless\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  }
 ]
}