{
 "title": "PCM",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "rate(L3_Cache_Misses{aggregate=\"system\"}[5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.50, rate(L3_Cache_Misses{aggregate=\"system\"}[5m]))",
     "legendFormat": "50th Percentile L3_Cache_Misses"
    },
    {
     "expr": "topk(5, rate(L3_Cache_Misses{aggregate=\"system\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rate(L3_Cache_Misses{aggregate=\"system\"}[5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.50, rate(L2_Cache_Misses{aggregate=\"system\"}[5m]))",
     "legendFormat": "50th Percentile L3_Cache_Misses"
    },
    {
     "expr": "topk(5, rate(L2_Cache_Misses{aggregate=\"system\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rate(Package_Joules_Consumed{aggregate=\"system\"}[5m])",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.50, rate(Package_Joules_Consumed{aggregate=\"system\"}[5m]))",
     "legendFormat": "50th percentile Package_Joules_Consumed"
    },
    {
     "expr": "topk(5, rate(Package_Joules_Consumed{aggregate=\"system\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rate(DRAM_Joules_Consumed{aggregate=\"system\"}[5m])",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.50, rate(DRAM_Joules_Consumed{aggregate=\"system\"}[5m]))",
     "legendFormat": "50th percentile Package_Joules_Consumed"
    },
    {
     "expr": "topk(5, rate(DRAM_Joules_Consumed{aggregate=\"system\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 SMI Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, SMI_Count{aggregate=\"system\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "quantile(0.5, SMI_Count{aggregate=\"system\"})",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Bottom 10 SMI Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, SMI_Count{aggregate=\"system\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "quantile(0.5, SMI_Count{aggregate=\"system\"})",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Top 10 Memory_Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, Local_Memory_Bandwidth{aggregate=\"system\"})",
     "legendFormat": "Local {{instance}}"
    },
    {
     "expr": "topk(10, Remote_Memory_Bandwidth{aggregate=\"system\"})",
     "legendFormat": "Remote {{instance}}"
    }
   ]
  },
  {
   "title": "Bottom 10 Memory_Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, Local_Memory_Bandwidth{aggregate=\"system\"})",
     "legendFormat": "Local {{instance}}"
    },
    {
     "expr": "bottomk(10, Remote_Memory_Bandwidth{aggregate=\"system\"})",
     "legendFormat": "Remote {{instance}}"
    }
   ]
  },
  {
   "title": "C0 Residency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg(CStateResidency{aggregate=\"system\", index=\"0\"}) by (instance)",
     "legendFormat": "C0"
    }
   ]
  },
  {
   "title": "C6 Residency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg(CStateResidency{aggregate=\"system\", index=\"6\"}) by (instance)",
     "legendFormat": "C6"
    }
   ]
  },
  {
   "title": "Power (Top 5)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, Package_Joules_Consumed{aggregate=\"system\"})",
     "legendFormat": "Package_Joules_Consumed {{instance}}"
    }
   ]
  }
 ]
}