{
 "title": "Telemetry health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Prometheus k8s up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"prometheus-k8s\"})"
    }
   ]
  },
  {
   "title": "Prometheus node up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"prometheus-node\"})"
    }
   ]
  },
  {
   "title": "Prometheus telemetry up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"prometheus-telemetry\"})"
    }
   ]
  }
 ]
}