{
 "title": "Telemetry Alerts",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Active Control Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=\"node-exporter\", instance=~\"piv-infra0501|piv-infra0502|piv-infra0601|piv-infra0602|piv-infra0701|piv-infra0702\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus adapter monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=~\"prometheus-(adapter|operator)\"}"
    }
   ]
  },
  {
   "title": "Prometheus telemetry monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=~\"prometheus-telemetry\"}"
    }
   ]
  },
  {
   "title": "Prometheus k8s monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=~\"prometheus-k8s\"}"
    }
   ]
  },
  {
   "title": "Prometheus node monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=~\"prometheus-node\"}"
    }
   ]
  },
  {
   "title": "Fluentd-kafka  output errors (rdkafka2)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, increase(fluentd_output_status_num_errors{container=\"fluentd-kafka\", type=\"rdkafka2\"}[1m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(increase(fluentd_output_status_num_errors{container=\"fluentd-kafka\", type=\"rdkafka2\"}[1m]) > 0)",
     "legendFormat": "Total Failing Fluentds"
    }
   ]
  },
  {
   "title": "Fluentd-kafka output errors (other plugins)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, increase(fluentd_output_status_num_errors{container=\"fluentd-kafka\", type!=\"rdkafka2\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logstash - Qpool Events out rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(logstash_node_pipeline_events_out_total {job=~\".*logstash-bridge-[a-z]*\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logstash - SOL Events out rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(logstash_node_pipeline_events_out_total {job=~\".*logstash-bridge-[a-z]*-sol\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Elasticsearch health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:868",
       "fake": true,
       "field": "@timestamp",
       "id": "6",
       "settings": { "interval": "15m", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:128",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heartbeats - Mismatch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "qpool",
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:289",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.container_name:\"node-heartbeat\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "critical-qpool",
     "bucketAggs": [
      {
       "$$hashKey": "object:1699",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1697", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container_name:\"node-heartbeat\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:289",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.container_name:\"node-heartbeat\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heartbeats - Critical",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:289",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.container_name:\"node-heartbeat\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Critical Elasticsearch health",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:868",
       "fake": true,
       "field": "@timestamp",
       "id": "6",
       "settings": { "interval": "15m", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:128",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "fluentd up on ive-infra nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code" }
   ]
  }
 ]
}