kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-prom-config-v0.1.6
  namespace: mgmt
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
{{range $path, $_ := $.Files.Glob "config/**.conf"}}
{{$path | base | indent 2}}: |-
{{tpl ($.Files.Get $path) $ | indent 4}}  
{{end}}
{{range $path, $_ := $.Files.Glob "tmp/shared/config/**.conf"}}
{{$path | base | indent 2}}: |-
{{tpl ($.Files.Get $path) $ | indent 4}}  
{{end}}
