apiVersion: v1
kind: ConfigMap
metadata:
  name: node-problem-detector-config
  namespace: kube-system
data:
  kernel-monitor.json: |
    {
        "plugin": "kmsg",
        "logPath": "/dev/kmsg",
        "lookback": "5m",
        "bufferSize": 100,
        "source": "kernel-monitor",
        "rules": [
            {
                "type": "permanent",
                "reason": "Hardware Error",
                "pattern": "mce:.*"
            },
            {
                "type": "permanent",
                "reason": "Hardware Error",
                "pattern": "traps.*"
            },
            {
                "type": "permanent",
                "reason": "Hardware Error",
                "pattern": "runc:*"
            },
            {
                "type": "permanent",
                "reason": "Hardware Error",
                "pattern": "Code:*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "oom-kill:.*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "Out of memory:.*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "oom_reaper:.*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "Kill process \\d+ (.+) score \\d+ or sacrifice child\\nKilled process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB, file-rss:\\d+kB.*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "task \\S+:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "BUG: unable to handle kernel NULL pointer dereference at .*"
            },
            {
                "type": "temporary",
                "reason": "Hardware Error",
                "pattern": "divide error: 0000 \\[#\\d+\\] SMP"
            }
        ]
    }
  mce-monitor.json: |
    {
        "plugin": "journald",
        "pluginConfig": {
            "source": "mcelog"
        },
        "logPath": "/var/log/journal",
        "lookback": "5m",
        "bufferSize": 100,
        "source": "mce-monitor",
        "conditions": [],
        "rules": [
            {
                "type": "permanent",
                "reason": "Hardware Error",
                "pattern": "Hardware event.*"
            }
        ]
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npd-binding
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npd-v0.6.3
  namespace: kube-system
  labels:
    k8s-app: node-problem-detector
    version: v0.6.3
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: node-problem-detector
      version: v0.6.3
  template:
    metadata:
      labels:
        k8s-app: node-problem-detector
        version: v0.6.3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: node-problem-detector
        image: prt-registry.sova.intel.com/node-problem-detector:v0.6.3
        command:
        - "/bin/sh"
        - "-c"
        - "exec /node-problem-detector --logtostderr --system-log-monitors=/config/kernel-monitor.json,/config/mce-monitor.json"
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "20m"
            memory: "20Mi"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: log
        hostPath:
          path: /var/log/
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: "FileOrCreate"
      - name: config
        configMap:
          name: node-problem-detector-config
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: mce-monitor.json
            path: mce-monitor.json
      serviceAccountName: node-problem-detector
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
