apiVersion: v1
kind: Service
metadata:
  name: cp-zookeeper-jmx-headless
  labels:
    app: cp-zookeeper
spec:
  ports:
    - port: 5556
      name: metrics
  clusterIP: None
  selector:
    app: cp-zookeeper
