apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  labels:
    app: cp-kafka
    type: telemetry
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cp-kafka
          - cp-zookeeper
          - cp-ksql-server
