---
# Source: cp-ksql-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atscale-bmc-sol-cp-ksql-server
  labels:
    app: cp-ksql-server
    chart: cp-ksql-server-0.1.0
    release: atscale-bmc-sol
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-ksql-server
      release: atscale-bmc-sol
  template:
    metadata:
      labels:
        app: cp-ksql-server
        release: atscale-bmc-sol
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
      containers:
        - name: prometheus-jmx-exporter
          image: "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143"
          imagePullPolicy: "IfNotPresent"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - "5556"
          - /etc/jmx-ksql-server/jmx-ksql-server-prometheus.yml
          ports:
          - containerPort: 5556
          resources:
            {}
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-ksql-server
        - name: cp-ksql-server
          image: "confluentinc/cp-ksqldb-server:6.0.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: server
              containerPort: 8088
              protocol: TCP
            - containerPort: 5555
              name: jmx
          resources:
            {}
          volumeMounts:
          - name: ksql-queries
            mountPath: /etc/ksql/queries
          env:
          - name: KSQL_BOOTSTRAP_SERVERS
            value: PLAINTEXT://atscale-cp-kafka-headless:9092
          - name: KSQL_KSQL_SERVICE_ID
            value: atscale-bmc-sol
          - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
            value: http://atscale-bmc-sol-cp-schema-registry:8081
          - name: KSQL_HEAP_OPTS
            value: "-Xms512M -Xmx512M"
          - name: KSQL_KSQL_QUERIES_FILE
            value: /etc/ksql/queries/queries.sql
          - name: "KSQL_COMPRESSION_TYPE"
            value: "snappy"
          - name: "KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE"
            value: "false"
          - name: "KSQL_KSQL_INTERNAL_TOPIC_REPLICAS"
            value: "2"
          - name: "KSQL_KSQL_STREAMS_NUM_STANDBY_REPLICAS"
            value: "2"
          - name: "KSQL_KSQL_STREAMS_REPLICATION_FACTOR"
            value: "2"
          - name: "KSQL_MAX_REQUEST_SIZE"
            value: "12160530"
          - name: JMX_PORT
            value: "5555"
      volumes:
      - name: jmx-config
        configMap:
          name: atscale-bmc-sol-cp-ksql-server-jmx-configmap
      - name: ksql-queries
        configMap:
          name: atscale-bmc-sol-cp-ksql-server-ksql-queries-configmap
      nodeSelector:
        ksql: "true"
