---
# Source: fluentd-kafka/templates/fluentd-kafka-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluentd-kafka
  labels:
    k8s-app: fluentd-kafka
    type: telemetry
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-kafka
  namespaceSelector:
    matchNames:
      - mgmt
  podMetricsEndpoints:
  - port: metrics
    interval: 10s
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
