---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: NAMESPACE
  name: SANDSTONE_NAME
spec:
  selector:
    matchLabels:
      name: SANDSTONE_NAME
  template:
    metadata:
      labels:
        name: SANDSTONE_NAME
    spec:
      nodeSelector:
        SANDSTONE_NODE_LABEL: "true"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: aesmd
          emptyDir:
            medium: Memory
        - name: hostroot
          hostPath:
            path: /
            type: Directory
        - name: sgx
          hostPath:
            path: /dev/sgx
            type: Directory
        - name: devlog
          hostPath:
            path: /dev/log
            type: Socket
        - name: varlog
          hostPath:
            path: /var/log
        - name: ai-datasets
          hostPath:
            path: /home/dataset
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
      initContainers:
        - name: create-metadata
          image: REGISTRY/cluster-scope:v0.41
          command: ["/bin/bash"]
          args: ["-c", "mkdir -p /var/log/atscale; (echo '{\"name\": \"SANDSTONE_NAME\", \"runid\": \"ATSCALE_RUNID\"}' | tee -a /var/log/atscale/test-metadata.ndjson  | jq -c '. += {\"type\": \"test-metadata\"}'>/hostroot/dev/console &); \
                  sleep 5; \
                  echo run-start-indicator"]
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: hostroot
            mountPath: /hostroot

        - name: ai-datasets
          image: REGISTRY/sandstone:ai-datasets-v0.1
          command: ["/update_datasets"]
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: ai-datasets
              mountPath: /home/dataset

      containers:
      - name: pnp-ai-inference
        image: REGISTRY/sandstone:DOCKER_TAG
        imagePullPolicy: Always
        volumeMounts:
            - name: sys
              mountPath: /sys
            - name: ai-datasets
              mountPath: /home/dataset
        #run-specific uses env vars for params
        command: ["/tests/scripts/run-specific.sh"]
        env:
          - name: RUN_MODE
            value: "inference"
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/testdone
            # Wait for 30s before checking for the first time
            # then probe for completion every 5 seconds
          initialDelaySeconds: 30
          periodSeconds: 5
        securityContext:
          privileged: true

      - name: pnp-ai-training
        image: REGISTRY/sandstone:DOCKER_TAG
        imagePullPolicy: Always
        volumeMounts:
            - name: sys
              mountPath: /sys
            - name: ai-datasets
              mountPath: /home/dataset
        #run-specific uses env vars for params
        command: ["/tests/scripts/run-specific.sh"]
        env:
          - name: RUN_MODE
            value: "training"
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/testdone
            # Wait for 30s before checking for the first time
            # then probe for completion every 5 seconds
          initialDelaySeconds: 30
          periodSeconds: 5
        securityContext:
          privileged: true
