---
# Source: cp-helm-charts/charts/cp-kafka/templates/nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atscale-cp-kafka-0-nodeport
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: atscale
    heritage: Helm
    pod: atscale-cp-kafka-0
spec:
  type: NodePort
  ports:
    - name: external-broker
      port: 19092
      targetPort: 31090
      nodePort: 31090
      protocol: TCP
  selector:
    app: cp-kafka
    release: atscale
    statefulset.kubernetes.io/pod-name: "atscale-cp-kafka-0"
---
# Source: cp-helm-charts/charts/cp-kafka/templates/nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atscale-cp-kafka-1-nodeport
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: atscale
    heritage: Helm
    pod: atscale-cp-kafka-1
spec:
  type: NodePort
  ports:
    - name: external-broker
      port: 19092
      targetPort: 31091
      nodePort: 31091
      protocol: TCP
  selector:
    app: cp-kafka
    release: atscale
    statefulset.kubernetes.io/pod-name: "atscale-cp-kafka-1"
---
# Source: cp-helm-charts/charts/cp-kafka/templates/nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atscale-cp-kafka-2-nodeport
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: atscale
    heritage: Helm
    pod: atscale-cp-kafka-2
spec:
  type: NodePort
  ports:
    - name: external-broker
      port: 19092
      targetPort: 31092
      nodePort: 31092
      protocol: TCP
  selector:
    app: cp-kafka
    release: atscale
    statefulset.kubernetes.io/pod-name: "atscale-cp-kafka-2"
