apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: labeling-validator-webhook
    kind: validator
  name: labeling-validator-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: 
    service:
      name: labeling-validator-webhook
      namespace: mgmt
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: labeling-validator-webhook.mgmt.xyz
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - nodes
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
