---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-msr-configmap
  namespace: mgmt
data:
  msrs: |-
    check_change:
      - 1b1h,13:12,0
      - 1b2h
    monitor:
      - 8b
      - 4f
      - 1ad
      - 771
