{
 "title": "IPMI Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,1m,5m,10m,30m,1h,3h,6h,12h,1d,2d,3d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(ipmi_temperature_celsius, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\"Core.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "BMC Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\"BMC.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Die Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\"Die.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "DTS Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\"DTS.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "DTS Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\".*Temp.*\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\".*Board.*\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\".*NVMe.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\",name=~\"DIMM.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance=\"$host\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Voltages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=\"$host\",name=~\".*CPU.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "All Voltages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=\"$host\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "All Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$host\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}