---
# Source: fluentd-kafka/templates/fluentd-kafka-configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-kafka-config-v0.1.6-default
  namespace: mgmt
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:

  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>
    
    <match raw.kubernetes.var.log.containers.**fluent**.log>
      @type null
    </match>
    
    <match raw.kubernetes.var.log.containers.**kafka**.log>
      @type null
    </match>
    
    # <match raw.kubernetes.var.log.containers.**node-fingerprint**.log>
    #   @type null
    # </match>
    
    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>
      

  forward.input.conf: |-
    # Takes the messages sent over TCP
    <source>
      @type forward
    </source>
      

  monitoring.conf: |-
    # Prometheus Exporter Plugin
    # input plugin that exports metrics
    <source>
      @type prometheus
    </source>
    
    <source>
      @type monitor_agent
      port 24210
    </source>
    
    # input plugin that collects metrics from MonitorAgent
    <source>
      @type prometheus_monitor
      <labels>
        host ${hostname}
      </labels>
    </source>
    
    # input plugin that collects metrics for output plugin
    <source>
      @type prometheus_output_monitor
      <labels>
        host ${hostname}
      </labels>
    </source>
    
    # input plugin that collects metrics for in_tail plugin
    <source>
      @type prometheus_tail_monitor
      <labels>
        host ${hostname}
      </labels>
    </source>
      

  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    <filter **>
      @type record_transformer
      <record>
        test TEST_NOTSET #subst test id here
        runid RUNID_NOTSET #subst run id here
        cluster-name 
        subcluster-name 
      </record>
    </filter>
    
    <filter kubernetes.var.log.containers.**shc-chyenne**.log>
      @type record_transformer
      enable_ruby
      <record>
         #Strip ANSI colors. Reference: https://en.wikipedia.org/wiki/ANSI_escape_code
         #Similar to the following fluentd plugin
         #https://github.com/mattheworiordan/fluent-plugin-color-stripper
         log ${record["log"].gsub(/\033\[\d{1,2}(;\d{1,2}){0,2}[mGK]/, '')}
      </record>
    </filter>
    
    # TBD: Add heartbeat counter to help verifying data transfer
    # This requires some more testing & debugging
    # <match kubernetes.**>
    #   @type rewrite_tag_filter
    #   <rule>
    #     key log
    #     pattern /^[\s]*Heartbeat:/
    #     tag heartbeat
    #   </rule>
    #   <rule>
    #     key tag
    #     pattern /.+/
    #     tag other
    #   </rule>
    # </match>
    
    # <filter heartbeat>
    #   @type parser
    #   key_name log
    #   reserve_data true
    #   reserve_time true
    #   <parse>
    #     @type regexp
    #     expression /^[\s]*Heartbeat:[\s]*(?<COUNT>[0-9]+).*/
    #     types COUNT:integer
    #   </parse>
    # </filter>
    
    
    # <filter heartbeat>
    #   @type prometheus
    #   <metric>
    #     name fluentd_input_status_heartbeat_count
    #     type gauge
    #     key COUNT
    #     desc Heartbeat counter
    #     <labels>
    #       tag ${tag}
    #       hostname ${hostname}
    #     </labels>
    #   </metric>
    # </filter>
    
    <filter **>
      @type prometheus
      <metric>
        name fluentd_input_status_num_records_total
        type counter
        desc The total number of incoming records
        <labels>
          tag ${tag}
          hostname ${hostname}
        </labels>
      </metric>
    </filter>
    
    # Concatenate multi-line logs
    <filter **>
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>
    
    <match **>
      @type kafka_buffered
      @log_level info
    
      brokers 172.10.0.5:31090,172.10.0.36:31091,172.10.0.67:31092,
      default_topic atscale
      use_event_time true
      output_include_tag true
      max_send_limit_bytes 10485760
      kafka_agg_max_bytes 10485760
      kafka_agg_max_messages 5000
      compression_codec snappy
      get_kafka_client_log true
      idempotent true
    
      buffer_type file
      buffer_path /var/log/fluentd-buffers/fluentd-kafka.buffer
      flush_mode interval
      retry_type exponential_backoff
      flush_thread_count 3
      flush_interval 30s
      retry_timeout 1h
      retry_max_interval 120000
      buffer_chunk_limit_size 10M
      buffer_queue_limit_length 8
      buffer_overflow_action block
    
    </match>
      

  system.conf: |-
    <system>
      @log_level fatal
      root_dir /tmp/fluentd-buffers/
      rpc_endpoint 0.0.0.0:24444
    </system>
      

  system.input.conf: |-
    # Example:
    # 2015-12-21 23:17:22,066 [salt.state       ][INFO    ] Completed state [net.ipv4.ip_forward] at time 23:17:22.066081
    <source>
      @id minion
      @type tail
      format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
      time_format %Y-%m-%d %H:%M:%S
      path /var/log/salt/minion
      pos_file /var/log/fluentd-kafka/salt.pos
      tag salt
    </source>
    
    # Example:
    # Dec 21 23:17:22 gke-foo-1-1-4b5cbd14-node-4eoj startupscript: Finished running startup script /var/run/google.startup.script
    <source>
      @id startupscript.log
      @type tail
      format syslog
      path /var/log/startupscript.log
      pos_file /var/log/fluentd-kafka/es-startupscript.log.pos
      tag startupscript
    </source>
    
    # Examples:
    # time="2016-02-04T06:51:03.053580605Z" level=info msg="GET /containers/json"
    # time="2016-02-04T07:53:57.505612354Z" level=error msg="HTTP Error" err="No such image: -f" statusCode=404
    # TODO(random-liu): Remove this after cri container runtime rolls out.
    <source>
      @id docker.log
      @type tail
      format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      path /var/log/docker.log
      pos_file /var/log/fluentd-kafka/es-docker.log.pos
      tag docker
    </source>
    
    # Example:
    # 2016/02/04 06:52:38 filePurge: successfully removed file /var/etcd/data/member/wal/00000000000006d0-00000000010a23d1.wal
    <source>
      @id etcd.log
      @type tail
      # Not parsing this, because it doesn't have anything particularly useful to
      # parse out of it (like severities).
      format none
      path /var/log/etcd.log
      pos_file /var/log/fluentd-kafka/es-etcd.log.pos
      tag etcd
    </source>
    
    # Multi-line parsing is required for all the kube logs because very large log
    # statements, such as those that include entire object bodies, get split into
    # multiple lines by glog.
    
    # Example:
    # I0204 07:32:30.020537    3368 server.go:1048] POST /stats/container/: (13.972191ms) 200 [[Go-http-client/1.1] 10.244.1.3:40537]
    <source>
      @id kubelet.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/kubelet.log
      pos_file /var/log/es-kubelet.log.pos
      tag kubelet
    </source>
    
    # Example:
    # I1118 21:26:53.975789       6 proxier.go:1096] Port "nodePort for kube-system/default-http-backend:http" (:31429/tcp) was open before and is still needed
    <source>
      @id kube-proxy.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/kube-proxy.log
      pos_file /var/log/fluentd-kafka/es-kube-proxy.log.pos
      tag kube-proxy
    </source>
    
    # Example:
    # I0204 07:00:19.604280       5 handlers.go:131] GET /api/v1/nodes: (1.624207ms) 200 [[kube-controller-manager/v1.1.3 (linux/amd64) kubernetes/6a81b50] 127.0.0.1:38266]
    <source>
      @id kube-apiserver.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/kube-apiserver.log
      pos_file /var/log/fluentd-kafka/es-kube-apiserver.log.pos
      tag kube-apiserver
    </source>
    
    # Example:
    # I0204 06:55:31.872680       5 servicecontroller.go:277] LB already exists and doesn't need update for service kube-system/kube-ui
    <source>
      @id kube-controller-manager.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/kube-controller-manager.log
      pos_file /var/log/fluentd-kafka/es-kube-controller-manager.log.pos
      tag kube-controller-manager
    </source>
    
    # Example:
    # W0204 06:49:18.239674       7 reflector.go:245] pkg/scheduler/factory/factory.go:193: watch of *api.Service ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2578313/2577886]) [2579312]
    <source>
      @id kube-scheduler.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/kube-scheduler.log
      pos_file /var/log/fluentd-kafka/es-kube-scheduler.log.pos
      tag kube-scheduler
    </source>
    
    # Example:
    # I0603 15:31:05.793605       6 cluster_manager.go:230] Reading config from path /etc/gce.conf
    <source>
      @id glbc.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/glbc.log
      pos_file /var/log/fluentd-kafka/es-glbc.log.pos
      tag glbc
    </source>
    
    # Example:
    # I0603 15:31:05.793605       6 cluster_manager.go:230] Reading config from path /etc/gce.conf
    <source>
      @id cluster-autoscaler.log
      @type tail
      format multiline
      multiline_flush_interval 5s
      format_firstline /^\w\d{4}/
      format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
      time_format %m%d %H:%M:%S.%N
      path /var/log/cluster-autoscaler.log
      pos_file /var/log/fluentd-kafka/es-cluster-autoscaler.log.pos
      tag cluster-autoscaler
    </source>
    
    # Logs from systemd-journal for interesting services.
    # TODO(random-liu): Remove this after cri container runtime rolls out.
    <source>
      @id journald-docker
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "docker.service" }]
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-kafka/journald-docker.pos
      </storage>
      read_from_head true
      tag docker
    </source>
    
    <source>
      @id journald-container-runtime
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "crio.service" }]
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-kafka/journald-container-runtime.pos
      </storage>
      read_from_head true
      tag container-runtime
    </source>
    
    # <source>
    #   @type systemd
    #   path /var/log/journal
    #   matches [{"SYSLOG_IDENTIFIER": "kata-runtime"}, {"SYSLOG_IDENTIFIER": "kata-proxy"}, {"SYSLOG_IDENTIFIER": "kata-shim"}]
    #   tag kata-containers
    #   <entry>
    #     fields_strip_underscores true
    #     fields_lowercase true
    #   </entry>
    # </source>
    
    <source>
      @id journald-kubelet
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "kubelet.service", "PRIORITY": 4 }]
      <storage>
        @type local
        persistent true
        path /var/log/journald-kubelet.pos
      </storage>
      read_from_head true
      tag kubelet
    </source>
    
    <source>
      @id journald-mcelog
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "mcelog.service" }]
      <storage>
        @type local
        persistent true
        path /var/log/journald-mcelog.pos
      </storage>
      read_from_head true
      tag mcelog
    </source>
    
    <source>
      @id journald-containerd
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "containerd.service", "PRIORITY": 4 }]
      <storage>
        @type local
        persistent true
        path /var/log/journald-containerd.pos
      </storage>
      read_from_head true
      tag containerd
    </source>
    
    <source>
      @id journald-node-problem-detector
      @type systemd
      matches [{ "_SYSTEMD_UNIT": "node-problem-detector.service" }]
      <storage>
        @type local
        persistent true
        path /var/log/fluentd-kafka/journald-node-problem-detector.pos
      </storage>
      read_from_head true
      tag node-problem-detector
    </source>
    
    <source>
      @id kernel
      @type systemd
      matches [{ "_TRANSPORT": "kernel" }]
      <storage>
        @type local
        persistent true
        path /var/log/kernel.pos
      </storage>
      read_from_head true
      tag kernel
    </source>
