apiVersion: apps/v1
kind:   DaemonSet
metadata:
  name: logstash-bridge-{{.Values.name}}
  labels:
    k8s-app: logstash-bridge-{{.Values.name}}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: logstash-bridge-{{.Values.name}}
  template:
    metadata:
      labels:
        k8s-app: logstash-bridge-{{.Values.name}}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      nodeSelector:
        logstash-bridge-{{.Values.name}}: "true"
      containers:
      - name: logstash-exporter
        image: bitnami/logstash-exporter
        ports:
          - containerPort: 9198
            name: exporter
      - name: logstash-bridge
        image: docker.elastic.co/logstash/logstash:7.16.1
        volumeMounts:
        - name: logstash-conf-vol
          mountPath: /usr/share/logstash/config
        - name: pipeline-conf-vol
          mountPath: /usr/share/logstash/pipeline
        {{if .Values.elasticsearch.cert}}
        - name: elastic-cert
          mountPath: /elastic-cert
        {{end}}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logstash-conf-vol
        configMap:
          name: logstash-bridge-{{.Values.name}}-config
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: pipeline-conf-vol
        configMap:
          name: logstash-bridge-{{.Values.name}}-config
          items:
          - key: logstash.conf
            path: logstash.conf
      {{if .Values.elasticsearch.cert}}
      - name: elastic-cert
        secret:
          secretName: {{.Values.elasticsearch.cert}} # Assume logstash runs in same k8s as ES
      {{end}}
