kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-bridge-config-v0.1.6-{{.Values.name}}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
{{range $path, $_ := $.Files.Glob "config/**.conf"}}
{{$path | base | indent 2}}: |-
{{tpl ($.Files.Get $path) $ | indent 4}}  
{{end}}
