---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluentd-bridge-{{.Values.name}}
  labels:
    k8s-app: fluentd-bridge-{{.Values.name}}
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-bridge-{{.Values.name}}
  namespaceSelector:
    matchNames:
    - default
  podMetricsEndpoints:
  - port: metrics
    interval: 10s
