apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fluentd-bridge-v2.2.1
  labels:
    k8s-app: fluentd-bridge
    version: v2.2.1
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      k8s-app: fluentd-bridge
      version: v2.2.1
  template:
    metadata:
      labels:
        k8s-app: fluentd-bridge
        version: v2.2.1
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      nodeSelector:
        fluentd-bridge: "true"
      containers:
      - name: fluentd-bridge
        ports:
        - name: metrics
          containerPort: 24231
          protocol: TCP
        image: sraghav1/fluentd-plugins:v3.0.1
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -vv
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-bridge-config-v0.1.6
