---
# Source: cp-helm-charts/charts/cp-zookeeper/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: atscale-cp-zookeeper-pdb
  labels:
    app: cp-zookeeper
    chart: cp-zookeeper-0.1.0
    release: atscale
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cp-zookeeper
      release: atscale
  maxUnavailable: 1
