apiVersion: v1
kind: ConfigMap
metadata:
  name: knob-monitor-config-map
  namespace: mgmt
data:
  BiosKnobs.ini: "[BiosKnobs]\nCpuMtoIWa=1\nEnableSgx=1\nEnableTme=1\nUmaBasedClustering=0\nVTdSupport=1\nPrmrrSize=0x400000000\n"
