apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterhealth
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: clusterhealth
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clusterhealth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterhealth
subjects:
- kind: ServiceAccount
  name: clusterhealth
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: clusterhealth-cm
  namespace: kube-system
data:
  config.json: |
    {
      "locations": ["opusa","op20lmain1","op20lmain2","op20lmain3","op20lmain4"],
      "es_index": "health",
      "es_host": "https://10.250.0.197:9200",
      "es_user": "paiv_admin",
      "es_pass": "password",
      "es_use_ssl": true,
      "es_cacert": "/elastic-cert/ca.crt",
      "interval": 10
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterhealth
  namespace: kube-system
  labels:
    app: clusterhealth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterhealth
  template:
    metadata:
      labels:
        app: clusterhealth
        tier: control-plane-addons
    spec:
      nodeSelector:
        nodetype: telemetry
      containers:
        - name: cluster-health
          image: prt-registry.sova.intel.com/cluster-health:v0.77
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /etc/clusterhealth
          - name: elastic-cert
            mountPath: /elastic-cert
      serviceAccount: clusterhealth
      volumes:
        - name: config-volume
          configMap:
            name: clusterhealth-cm
        - name: elastic-cert
          secret:
            secretName: atscale-es-cert
