{
 "title": "Health - Day Scale",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "HealthFilters" },
   { "name": "QpoolFilters" },
   { "name": "location", "query": "l10b2,zp31l10b01,zp31l10b02" }
  ]
 },
 "panels": [
  {
   "title": "Health - Nodes per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4412",
       "fake": true,
       "field": "pool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:4396",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "6h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4394",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Host Status - Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:39",
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:18",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:16",
       "field": "name.keyword",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1421",
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 30
       },
       "type": "moving_avg"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - NotReady by Stepping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3741",
       "fake": true,
       "field": "clusterscope.0.stepping.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3720",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3718",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location and status.keyword:NotReady",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Host Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:39",
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:18",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:16",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per node - Top 20",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "kubernetes.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location:$location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Reboot count - qpool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:114",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:112",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "container-name:node-heartbeat and log:\"Heartbeat: 0\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per node - l10b2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "kubernetes.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location: l10b2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - Power Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3741",
       "fake": true,
       "field": "clusterscope.powerStatus.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3720",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3718",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per node zp31l10b01",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "kubernetes.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "12h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location: zp31l10b01",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - BMC Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "clusterscope.bmcAvailable.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "metadata.cscope.pool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "12h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location:$location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - K8s Hosts with issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3920",
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "$$hashKey": "object:3931",
          "label": "Disk Pressure",
          "query": "k8s.disk_pressure.keyword: True"
         },
         {
          "$$hashKey": "object:3934",
          "label": "Memory Pressure",
          "query": "k8s.memory_pressure.keyword: True"
         },
         { "$$hashKey": "object:3937", "label": "PID Pressure", "query": "k8s.pid_pressure.keyword: True" },
         {
          "$$hashKey": "object:3943",
          "label": "Kubelet NotReady",
          "query": "k8s.kubelet_ready.keyword: False"
         }
        ]
       },
       "type": "filters"
      },
      {
       "$$hashKey": "object:18",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:16",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Test starts by pool - top 100",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:722",
       "fake": true,
       "field": "metadata.cscope.pool.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:702",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "3h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:700",
       "field": "metadata.test.runid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "metadata.cscope.location:$location and log:\"test-start-indicator\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "metadata.cscope.location.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - CPLD Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3741",
       "fake": true,
       "field": "clusterscope.cpldVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3720",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3718",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per test name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "metadata.test.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "6h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location:$location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - NotReady by CPLD Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3741",
       "fake": true,
       "field": "clusterscope.cpldVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3720",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3718",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location and status.keyword:NotReady",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Nodes per test name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "metadata.test.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "6h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "metadata.cscope.location:$location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - Microcode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "clusterscope.microcode.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "qpool - Docs per test name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2208",
       "fake": true,
       "field": "kubernetes.container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2158",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "6h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2156",
       "field": "pool.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metadata.cscope.location: $location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health - QDF 0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "clusterscope.0.qdf.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - K8s / Clusterscope Difference",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "K8s Hosts",
     "bucketAggs": [
      {
       "$$hashKey": "object:90",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:88",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Clusterscope Hosts",
     "bucketAggs": [
      {
       "$$hashKey": "object:63",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:61",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "clusterscope.name: *",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Steppings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "clusterscope.0.stepping.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location: $location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Kubelet versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "k8s.node_info.kubeletVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Bios Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "clusterscope.biosVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location: $location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Containerd versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "k8s.node_info.containerRuntimeVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location: $location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - Kernel Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "k8s.node_info.kernelVersion.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location:$location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nodes by pool state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:310",
       "fake": true,
       "field": "poolinfo.state.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:227",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:225",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Health - OS Image",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1717",
       "fake": true,
       "field": "k8s.node_info.osImage.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1693",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1691",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "location: $location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nodes by pool owner",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:310",
       "fake": true,
       "field": "poolinfo.assignto.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:227",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:225",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nodes by pool subcluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:310",
       "fake": true,
       "field": "poolinfo.subcluster.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:227",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:225",
       "field": "name.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}