---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubenurse
  labels:
    name: kubenurse
    type: node
spec:
  selector:
    matchLabels:
      name: kubenurse
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - port: metrics
    interval: 10s
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
