apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sol-collector.fullname" . }}-bmc
  labels:
{{ include "sol-collector.labels" . | indent 4 }}
data:
  redfish_user: {{ $.Values.redfish_user | b64enc }}
  redfish_password: {{ $.Values.redfish_password | b64enc }}
  ipmi_user: {{ $.Values.ipmi_user | b64enc }}
  ipmi_password: {{ $.Values.ipmi_password | b64enc }}
