apiVersion: v1
kind: Service
metadata:
  name: {{ include "sol-collector.fullname" . }}-ipmi
  labels:
{{ include "sol-collector.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sol-collector.name" . }}-ipmi
    app.kubernetes.io/instance: {{ .Release.Name }}
