{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sol-collector.serviceAccountName" . }}
  labels:
{{ include "sol-collector.labels" . | indent 4 }}
{{- end -}}
